spring:
  application:
    name: WorldCast

  ai:
    model:
      chat: vertexai
    vertex:
      ai:
        gemini:
          project-id: ${GCLOUD_PROJECT_ID:velvety-rookery-465515-u1}
          location: ${GCLOUD_PROJECT_LOCATION:us-central1}
          chat:
            options:
              model: gemini-2.5-flash-preview-04-17
              google-search-retrieval: true
              temperature: 1.0

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms

weather:
  api-key: ${WEATHER_API_KEY:TRKgIPds6btew6GbitkkXgOwOHmtIoUV}
  cache:
    prefix: worldcast
    ttl: 300 # 5 minutes
