---
server:
  port: "${SERVER_PORT:8080}"
spring:
  application:
    name: "WorldCast"
  ai:
    openai:
      api-key: "${GEMINI_API_KEY}"
      chat:
        base-url: "https://generativelanguage.googleapis.com"
        completions-path: "/v1beta/openai/chat/completions"
        options:
          model: "gemini-2.5-flash"
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  cache:
    type: "composite"
    cache-names:
      - "weather-cache"
    redis:
      time-to-live: 300000
      cache-null-values: false
      key-prefix: "worldcast:"
      use-key-prefix: true
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
      database: 0
      timeout: "2000ms"
      connect-timeout: "1000ms"
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
weather:
  api-key: "${WEATHER_API_KEY}"
  cache:
    prefix: "worldcast"
    ttl: 300
